name: Generate ubuntu builder images
# Generates an image that encapsulate an environment on which it is possible to build psibase.

env:
  GITHUB_OUTPUT: ""

on:
  workflow_call:
    inputs:
      is_pr:
        description: "Is 'true' if running in the context of a PR"
        type: boolean
        required: true
        default: true
      ubuntu_version:
        description: "On what version of ubuntu should the build run?"
        type: string
        required: true
        default: "2204"

jobs:
  ubuntu-builder:
    name: psibase-builder-ubuntu-${{ inputs.ubuntu_version }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: false
          fetch-depth: 0

      - name: Preparation
        id: prep
        run: |
          OWNER="${{ github.repository_owner }}"
          IMAGE="psibase-builder-ubuntu-${{ inputs.ubuntu_version }}"
          REGISTRY="ghcr.io"
          TAG="${{ github.sha }}"

          TAGS="${REGISTRY}/${OWNER}/${IMAGE}:${TAG}"
          echo "tags=${TAGS,,}" >> $GITHUB_OUTPUT

      - name: Building ${{ steps.prep.outputs.tags }}
        run: true

      - name: Config docker buildx network
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug

      - name: Login in to registry
        if: ${{ !inputs.is_pr }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Publish Image
        if: ${{ !inputs.is_pr }}
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          file: docker/ubuntu-${{ inputs.ubuntu_version }}-builder.Dockerfile
          tags: ${{ steps.prep.outputs.tags }}
          platforms: linux/amd64
          outputs: type=image,annotation-index.org.opencontainers.image.description=Psibase build environment based on Ubuntu ${{ inputs.ubuntu_version }}
    
      - name: (PR Only) - Build image archive
        if: ${{ inputs.is_pr }}
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/ubuntu-${{ inputs.ubuntu_version }}-builder.Dockerfile
          tags: ${{ steps.prep.outputs.tags }}
          platforms: linux/amd64
          outputs: type=docker,dest=builder-${{ inputs.ubuntu_version }}-image.tar

      - name: (PR only) - Upload image archive as artifact
        if: ${{ inputs.is_pr }}
        uses: actions/upload-artifact@v4
        with:
          name: builder-${{ inputs.ubuntu_version }}-image
          path: builder-${{ inputs.ubuntu_version }}-image.tar
          retention-days: 1
