name: Generate contributor image

env:
  GITHUB_OUTPUT: ""

on:
  workflow_call:
    inputs:
      is_pr:
        description: "Is 'true' if running in the context of a PR"
        type: boolean
        required: true
        default: true

jobs:
  psibase-contributor:
    name: psibase-contributor
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: false
          fetch-depth: 0

      - name: Free up runner space
        run: bash ${GITHUB_WORKSPACE}/.github/scripts/free-disk-space.sh

      - name: Preparation
        id: prep
        run: |
          OWNER="${{ github.repository_owner }}"
          IMAGE="psibase-contributor"
          if [[ "${{ inputs.is_pr }}" == "true" ]]; then
            REGISTRY="localhost:5000"
            TAG="latest"
          else
            REGISTRY="ghcr.io"
            TAG="${{ github.sha }}"
          fi
          TAGS="${REGISTRY}/${OWNER}/${IMAGE}:${TAG}"
          echo "tags=${TAGS,,}" >> $GITHUB_OUTPUT

      - name: Building ${{ steps.prep.outputs.tags }}
        run: true

      - name: (PR only) - Config docker buildx network
        if: ${{ inputs.is_pr }}
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug
          driver-opts: network=host

      - name: Login in to registry
        if: ${{ !inputs.is_pr }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: (PR only) - Download contributor base image from artifact
        if: ${{ inputs.is_pr }}
        uses: actions/download-artifact@v4
        with:
          name: builder-2204-image

      - name: (PR only) - Install downloaded image to docker
        if: ${{ inputs.is_pr }}
        run: |
          docker load -i builder-2204-image.tar
          echo "Local docker images:"
          docker images
      
      - name: (PR only) - Push image to local registry
        run: |
          docker push localhost:5000/gofractally/psibase-builder-ubuntu-2204:latest

      - name: Set BASE_IMAGE
        id: base_image
        run: |
          if [[ "${{ inputs.is_pr }}" == "true" ]]; then
            echo "BASE_IMAGE=localhost:5000/gofractally/psibase-builder-ubuntu-2204:latest" >> $GITHUB_OUTPUT
            echo "TOOL_CONFIG_IMAGE=localhost:5000/gofractally/https-tool-config:latest" >> $GITHUB_OUTPUT
          else
            echo "BASE_IMAGE=ghcr.io/gofractally/psibase-builder-ubuntu-2204:${{ github.sha }}" >> $GITHUB_OUTPUT
            echo "TOOL_CONFIG_IMAGE=ghcr.io/gofractally/https-tool-config:${{ github.sha }}" >> $GITHUB_OUTPUT
          fi

      - name: Build & Publish Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          build-args: |
            BASE_IMAGE=${{ steps.base_image.outputs.BASE_IMAGE }}
            TOOL_CONFIG_IMAGE=${{ steps.base_image.outputs.TOOL_CONFIG_IMAGE }}
          file: docker/psibase-contributor.Dockerfile
          tags: ${{ steps.prep.outputs.tags }}
          platforms: linux/amd64
          outputs: type=image,annotation-index.org.opencontainers.image.description=Psibase development environment

      - name: (PR only) - Save docker image to archive
        if: ${{ inputs.is_pr }}
        run: |
          rm builder-2204-image.tar
          docker pull ${{ steps.prep.outputs.tags }}
          docker save ${{ steps.prep.outputs.tags }} -o pr-psibase_contributor.tar

      - name: (PR only) - Upload docker image archive as artifact
        if: ${{ inputs.is_pr }}
        uses: actions/upload-artifact@v4
        with:
          name: pr-psibase_contributor
          path: pr-psibase_contributor.tar
          retention-days: 1