name: Generate contributor image

env:
  GITHUB_OUTPUT: ""

on:
  workflow_call:
    inputs:
      is_pr:
        description: "Is 'true' if running in the context of a PR"
        type: boolean
        required: true
        default: true
      is_local_tools: 
        description: "Is 'true' if the tools image dependency should be satisfied by a local image"
        type: boolean
        required: true
        default: false
      is_local_base:
        description: "Is 'true' if the base image dependency should be satisfied by a local image"
        type: boolean
        required: true
        default: false

jobs:
  psibase-contributor:
    name: psibase-contributor
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: false
          fetch-depth: 0

      - name: Preparation
        id: prep
        run: |
          OWNER="${{ github.repository_owner }}"
          IMAGE="psibase-contributor"
          REGISTRY="ghcr.io"
          TAG="${{ github.sha }}"
          TAGS="${REGISTRY}/${OWNER}/${IMAGE}:${TAG}"
          echo "tags=${TAGS,,}" >> $GITHUB_OUTPUT

      - name: Config docker buildx
        if: ${{ !inputs.is_pr }}
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug

      - name: (PR only) - Config docker buildx host network
        if: ${{ inputs.is_pr }}
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
          driver-opts: network=host

      - name: Login in to registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Download local base image
        if: ${{ inputs.is_local_base }}
        uses: actions/download-artifact@v4
        with:
          name: builder-2204-image
      - name: Set BASE_IMAGE
        id: base_img
        run: |
          if [[ "${{ inputs.is_local_base }}" == "true" ]]; then
            docker load -i builder-2204-image.tar
            rm builder-2204-image.tar
            IMAGE=$(docker images --format "{{.Repository}}:{{.Tag}}" | head -n 1)
            LOCAL_TAG=localhost:5000/local_base_image:latest
            docker tag ${IMAGE} ${LOCAL_TAG}
            docker push ${LOCAL_TAG}
            echo "BASE_IMAGE=${LOCAL_TAG}" >> $GITHUB_OUTPUT
          else
            latest_tag=$(./.github/scripts/latest-tag.sh "gofractally/psibase-builder-ubuntu-2204")
            echo "BASE_IMAGE=ghcr.io/gofractally/psibase-builder-ubuntu-2204:${latest_tag}" >> $GITHUB_OUTPUT
          fi

      - name: Download local tools image
        if: ${{ inputs.is_local_tools }}
        uses: actions/download-artifact@v4
        with:
          name: https-tool-config-image
      - name: Set TOOL_CONFIG_IMAGE
        id: tool_cfg_img
        run: |
          if [[ "${{ inputs.is_local_tools }}" == "true" ]]; then
            docker load -i https-tool-config-image.tar
            rm https-tool-config-image.tar
            IMAGE=$(docker images --format "{{.Repository}}:{{.Tag}}" | head -n 1)
            LOCAL_TAG=localhost:5000/local_tools_image:latest
            docker tag ${IMAGE} ${LOCAL_TAG}
            docker push ${LOCAL_TAG}
            echo "TOOL_CONFIG_IMAGE=${LOCAL_TAG}" >> $GITHUB_OUTPUT
          else
            latest_tag=$(./.github/scripts/latest-tag.sh "gofractally/https-tool-config")
            echo "TOOL_CONFIG_IMAGE=ghcr.io/gofractally/https-tool-config:${latest_tag}" >> $GITHUB_OUTPUT
          fi

      - name: Build & publish ${{ steps.prep.outputs.tags }}
        if: ${{ !inputs.is_pr }}
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          build-args: |
            BASE_IMAGE=${{ steps.base_img.outputs.BASE_IMAGE }}
            TOOL_CONFIG_IMAGE=${{ steps.tool_cfg_img.outputs.TOOL_CONFIG_IMAGE }}
          file: docker/psibase-contributor.Dockerfile
          tags: ${{ steps.prep.outputs.tags }}
          platforms: linux/amd64
          outputs: type=image,annotation-index.org.opencontainers.image.description=Psibase development environment

      - name: (PR Only) - Build image archive
        if: ${{ inputs.is_pr }}
        uses: docker/build-push-action@v4
        with:
          context: .
          build-args: |
            BASE_IMAGE=${{ steps.base_img.outputs.BASE_IMAGE }}
            TOOL_CONFIG_IMAGE=${{ steps.tool_cfg_img.outputs.TOOL_CONFIG_IMAGE }}
          file: docker/psibase-contributor.Dockerfile
          tags: ${{ steps.prep.outputs.tags }}
          platforms: linux/amd64
          outputs: type=docker,dest=psibase_contributor.tar

      - name: (PR only) - Upload image archive as artifact
        if: ${{ inputs.is_pr }}
        uses: actions/upload-artifact@v4
        with:
          name: psibase_contributor
          path: psibase_contributor.tar
          retention-days: 1