name: Generate tool-config images

env:
  GITHUB_OUTPUT: ""

on:
  push:
    branches:
      - main
      - "release/*"
    paths:
      - "docker/tool-config.Dockerfile"
      - ".github/workflows/tool-config.yml"
      - "docker/conf/*"
  pull_request:
    types: [assigned, opened, synchronize, reopened, labeled]
    paths:
      - "docker/tool-config.Dockerfile"
      - ".github/workflows/tool-config.yml"
      - "docker/conf/*"

jobs:
  https-tool-config:
    name: https-tool-config
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: false
          fetch-depth: 0
      - name: Preparation
        id: prep
        run: |
          REGISTRY="ghcr.io"
          IMAGE="${REGISTRY}/${{ github.repository_owner }}/https-tool-config"
          TAGS="${IMAGE}:${{ github.sha }},${IMAGE}:latest"
          echo "tags=${TAGS,,}" >> $GITHUB_OUTPUT
      - name: Showtag
        id: showtag
        run: echo ${{ steps.prep.outputs.tags }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: 'arm64'
      - name: Docker Buildx setup
        uses: docker/setup-buildx-action@v2
      - name: Login in to registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & Publish Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/release/*') }}
          file: docker/tool-config.Dockerfile
          build-args: |
            protocol=https
          tags: ${{ steps.prep.outputs.tags }}
          platforms: linux/amd64,linux/arm64
          outputs: type=image,annotation-index.org.opencontainers.image.description=Config files for admin-sys dashboard tools connecting to psinode over https on 8080
  http-tool-config:
    name: http-tool-config
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: false
          fetch-depth: 0
      - name: Preparation
        id: prep
        run: |
          REGISTRY="ghcr.io"
          IMAGE="${REGISTRY}/${{ github.repository_owner }}/http-tool-config"
          TAGS="${IMAGE}:${{ github.sha }},${IMAGE}:latest"
          echo "tags=${TAGS,,}" >> $GITHUB_OUTPUT
      - name: Showtag
        id: showtag
        run: echo ${{ steps.prep.outputs.tags }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: 'arm64'
      - name: Docker Buildx setup
        uses: docker/setup-buildx-action@v2
      - name: Login in to registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & Publish Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/release/*') }}
          file: docker/tool-config.Dockerfile
          build-args: |
            protocol=http
          tags: ${{ steps.prep.outputs.tags }}
          platforms: linux/amd64,linux/arm64
          outputs: type=image,annotation-index.org.opencontainers.image.description=Config files for admin-sys dashboard tools connecting to psinode over http on 8080
