name: Generate tool-config image

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - "release/*"
    paths:
      - "docker/tool-config.Dockerfile"
      - ".github/workflows/tool-config.yml"
  pull_request:
    types: [assigned, opened, synchronize, reopened, labeled]
    paths:
      - "docker/tool-config.Dockerfile"
      - ".github/workflows/tool-config.yml"

jobs:
  tool-config:
    name: tool-config
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: false
          fetch-depth: 0
      - name: Preparation
        id: prep
        run: |
          REGISTRY="ghcr.io"
          IMAGE="${REGISTRY}/${{ github.repository_owner }}/tool-config"
          TAGS="${IMAGE}:${{ github.sha }}"
          echo ::set-output name=tags::${TAGS,,}
      - name: Showtag
        id: showtag
        run: echo ${{ steps.prep.outputs.tags }}
      - name: Docker Buildx setup
        uses: docker/setup-buildx-action@v2
      - name: Login in to registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & Publish Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          file: docker/tool-config.Dockerfile
          tags: ${{ steps.prep.outputs.tags }}
          platforms: linux/amd64
          outputs: type=image,annotation-index.org.opencontainers.image.description=Config files for admin-sys dashboard tools
