name: Generate tool-config images

env:
  GITHUB_OUTPUT: ""

on:
  workflow_call:

jobs:
  tool-config:
    name: tool-config
    strategy:
      matrix:
        protocol: ["http", "https"]
        runner: [ubuntu-latest, arm-runner-1]
        include:
        - platform: "linux/amd64"
          platform_short: "amd"
          runner: ubuntu-latest
        - platform: "linux/arm64"
          platform_short: "arm"
          runner: arm-runner-1
    runs-on: ${{ matrix.runner }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: false
          fetch-depth: 0

      - name: Preparation
        id: prep
        run: |
          OWNER="${{ github.repository_owner }}"
          IMAGE="${{ matrix.protocol }}-tool-config-${{ matrix.platform_short }}"
          REGISTRY="ghcr.io"
          TAG="${{ github.sha }}" 
          FQIMAGE="${REGISTRY}/${OWNER}/${IMAGE}:${TAG}"
          echo "image=${IMAGE,,}" >> $GITHUB_OUTPUT
          echo "fqImage=${FQIMAGE,,}" >> $GITHUB_OUTPUT

      - name: Building ${{ steps.prep.outputs.fqImage }}
        run: true

      - name: Runner ${{ matrix.runner }}
        run: true

      - name: Install docker
        if: matrix.runner == 'arm-runner-1'
        run: |
          sudo apt-get update
          sudo apt-get install -yq ca-certificates curl
          sudo install -m 0755 -d /etc/apt/keyrings
          sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
          sudo chmod a+r /etc/apt/keyrings/docker.asc
          
          # Add the repository to Apt sources:
          echo \
            "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
            $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
            sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update

          # Install
          sudo apt-get install -yq docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

          # Give current user permission to run docker without sudo
          sudo usermod -aG docker $USER
          sudo apt-get install -yq acl
          sudo setfacl --modify user:$USER:rw /var/run/docker.sock

      - name: Config docker buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug

      - name: Login in to registry
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Publish Image
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          file: docker/tool-config.Dockerfile
          build-args: |
            protocol=${{ matrix.protocol }}
          tags: ${{ steps.prep.outputs.fqImage }}
          platforms: ${{ matrix.platform }}
          outputs: |
            type=image
            annotation-index.org.opencontainers.image.description=Config files for admin dashboard tools connecting to psinode over ${{ matrix.protocol }}

      - name: (PR Only) - Build image archive
        if: ${{ github.event_name == 'pull_request' }}
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/tool-config.Dockerfile
          build-args: |
            protocol=${{ matrix.protocol }}
          tags: ${{ steps.prep.outputs.fqImage }}
          platforms: ${{ matrix.platform }}
          outputs: type=docker,dest=${{ steps.prep.outputs.image }}-image.tar

      - name: (PR only) - Upload image archive as artifact
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.prep.outputs.image }}-image
          path: ${{ steps.prep.outputs.image }}-image.tar
          retention-days: 1
  merge: 
    name: merge multi-platform images
    if: ${{ github.event_name != 'pull_request' }}
    strategy:
      matrix:
        protocol: ["http", "https"]
    runs-on: ubuntu-latest
    needs: tool-config
    steps:
      - name: Config docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login in to registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Preparation
        id: prep
        run: |
          REGISTRY="ghcr.io"
          OWNER="${{ github.repository_owner }}"
          IMAGE="${{ matrix.protocol }}-tool-config"
          TAG="${{ github.sha }}"
          FQIMAGE="${REGISTRY}/${OWNER}/${IMAGE}:${TAG}"
          echo "fqImage=${FQIMAGE,,}" >> $GITHUB_OUTPUT

          ARM_IMAGE="${{ matrix.protocol }}-tool-config-arm"
          FQIMAGE_ARM="${REGISTRY}/${OWNER}/${ARM_IMAGE}:${TAG}"
          echo "fqArmImage=${FQIMAGE_ARM,,}" >> $GITHUB_OUTPUT

          AMD_IMAGE="${{ matrix.protocol }}-tool-config-amd"
          FQIMAGE_AMD="${REGISTRY}/${OWNER}/${AMD_IMAGE}:${TAG}"
          echo "fqAmdImage=${FQIMAGE_AMD,,}" >> $GITHUB_OUTPUT

      - name: Push manifest
        uses: Noelware/docker-manifest-action@master
        with:
          inputs: ${{ steps.prep.outputs.fqImage }}
          images: ${{ steps.prep.outputs.fqArmImage }},${{ steps.prep.outputs.fqAmdImage }}
          push: true