name: Generate tool-config images

env:
  GITHUB_OUTPUT: ""

on:
  workflow_call:
    inputs:
      is_pr:
        description: "Is 'true' if running in the context of a PR"
        type: boolean
        required: true
        default: true

jobs:
  tool-config:
    name: tool-config
    runs-on: ubuntu-latest
    strategy:
      matrix:
        protocol: ["http", "https"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: false
          fetch-depth: 0

      - name: Free up runner space
        run: bash ${GITHUB_WORKSPACE}/.github/scripts/free-disk-space.sh

      - name: Preparation
        id: prep
        run: |
          OWNER="${{ github.repository_owner }}"
          IMAGE="${{ matrix.protocol }}-tool-config"
          if [[ "${{ inputs.is_pr }}" == "true" ]]; then
            REGISTRY="localhost:5000"
            TAG="latest"
          else
            REGISTRY="ghcr.io"
            TAG="${{ github.sha }}"
          fi
          TAGS="${REGISTRY}/${OWNER}/${IMAGE}:${TAG}"
          echo "tags=${TAGS,,}" >> $GITHUB_OUTPUT

      - name: Building ${{ steps.prep.outputs.tags }}
        run: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: 'arm64'

      - name: (PR only) - Config docker buildx network
        if: ${{ inputs.is_pr }}
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug
          driver-opts: network=host

      - name: Login in to registry
        if: ${{ !inputs.is_pr }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Publish Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          file: docker/tool-config.Dockerfile
          build-args: |
            protocol=${{ matrix.protocol }}
          tags: ${{ steps.prep.outputs.tags }}
          platforms: linux/amd64,linux/arm64
          outputs: type=image,annotation-index.org.opencontainers.image.description=Config files for admin-sys dashboard tools connecting to psinode over ${{ matrix.protocol }} on 8080

      - name: (PR only) - Save docker image to archive
        if: ${{ inputs.is_pr }}
        run: |
          docker pull ${{ steps.prep.outputs.tags }}
          docker save ${{ steps.prep.outputs.tags }} -o ${{ matrix.protocol }}-tool-config-image.tar

      - name: (PR only) - Upload docker image archive
        if: ${{ inputs.is_pr }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.protocol }}-tool-config-image
          path: ${{ matrix.protocol }}-tool-config-image.tar
          retention-days: 1
