name: ubuntu-1804-builder container

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - "release/*"
    paths:
      - "docker/ubuntu-1804-builder.Dockerfile"
      - ".github/workflows/ubuntu-1804-builder.yml"
  pull_request:
    types: [assigned, opened, synchronize, reopened, labeled]
    paths:
      - "docker/ubuntu-1804-builder.Dockerfile"
      - ".github/workflows/ubuntu-1804-builder.yml"

jobs:
  ubuntu-1804-builder:
    name: internal-ubuntu-1804-builder
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: false
          fetch-depth: 0

      - name: Preparation
        id: prep
        run: |
          REGISTRY="ghcr.io"
          IMAGE="${REGISTRY}/${{ github.repository_owner }}/internal-ubuntu-1804-builder"
          TAGS="${IMAGE}:${{ github.sha }}"
          echo ::set-output name=tags::${TAGS,,}

      - name: Showtag
        id: showtag
        run: echo ${{ steps.prep.outputs.tags }}

      - name: Docker Buildx setup
        uses: docker/setup-buildx-action@v1
        with:
          buildkitd-flags: --debug

      - name: Login in to registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Publish Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: docker/ubuntu-1804-builder.Dockerfile
          tags: ${{ steps.prep.outputs.tags }}
